name: flutter_action_test_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: 
  image_picker:
  permission_handler: 
  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.9
  image: ^3.1.3

  flutter_barcode_scanner: ^2.0.0

  web_socket_channel: ^2.1.0

  flutter_flavor: ^3.0.3

  bubble: ^1.2.1

  syncfusion_flutter_datagrid: ^19.3.55

  # state
  flutter_riverpod: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# flavor

flutter_flavor:
  dimensions:
    android: "flutter-flavor"
    ios: "flutter-flavor"

  flavors:
    # develop用
    dev:
      app:
        name: "Dev App"
      android:
        applicationId: "com.example.dev"
      ios:
        bundleId: "com.example.dev"

    # production用
    prod:
      app:
        name: "Prod App"
      android:
        applicationId: "com.example.prod"
      ios:
        bundleId: "com.example.prod"

# flavor generate command
# flutter pub run flutter_flavor:main
# flavor run command
# flutter run --flavor prod -t lib/main_prod.dart
# flutter run --flavor dev -t lib/main_dev.dart

# --flavor : ネイティブ側に伝える
# prod or dev  +  -t: Flutter のエントリーポイントを指定